// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesTodo.DAL;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotesTodo.Migrations
{
    [DbContext(typeof(TodoDb))]
    [Migration("20260306212900_initialCreate")]
    partial class initialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotesTodo.Models.ProjectMembership", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("TodoProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "TodoProjectId");

                    b.HasIndex("TodoProjectId");

                    b.ToTable("ProjectMemberships");
                });

            modelBuilder.Entity("NotesTodo.Models.SubTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Criticality")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TodoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TodoId");

                    b.ToTable("SubTasks");
                });

            modelBuilder.Entity("NotesTodo.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompletedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Criticality")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TodoProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("TodoProjectId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("NotesTodo.Models.TodoProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TodoProjects");
                });

            modelBuilder.Entity("NotesTodo.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SubTaskUser", b =>
                {
                    b.Property<int>("AssignedSubTasksId")
                        .HasColumnType("integer");

                    b.Property<int>("AssingedUsersId")
                        .HasColumnType("integer");

                    b.HasKey("AssignedSubTasksId", "AssingedUsersId");

                    b.HasIndex("AssingedUsersId");

                    b.ToTable("SubTaskUser");
                });

            modelBuilder.Entity("TodoUser", b =>
                {
                    b.Property<int>("AssignedTodosId")
                        .HasColumnType("integer");

                    b.Property<int>("AssignedUsersId")
                        .HasColumnType("integer");

                    b.HasKey("AssignedTodosId", "AssignedUsersId");

                    b.HasIndex("AssignedUsersId");

                    b.ToTable("TodoUser");
                });

            modelBuilder.Entity("NotesTodo.Models.ProjectMembership", b =>
                {
                    b.HasOne("NotesTodo.Models.TodoProject", "TodoProject")
                        .WithMany("Members")
                        .HasForeignKey("TodoProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesTodo.Models.User", "User")
                        .WithMany("ProjectMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TodoProject");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NotesTodo.Models.SubTask", b =>
                {
                    b.HasOne("NotesTodo.Models.Todo", "Todo")
                        .WithMany("SubTask")
                        .HasForeignKey("TodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Todo");
                });

            modelBuilder.Entity("NotesTodo.Models.Todo", b =>
                {
                    b.HasOne("NotesTodo.Models.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NotesTodo.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NotesTodo.Models.TodoProject", "TodoProject")
                        .WithMany("Todos")
                        .HasForeignKey("TodoProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompletedByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("TodoProject");
                });

            modelBuilder.Entity("SubTaskUser", b =>
                {
                    b.HasOne("NotesTodo.Models.SubTask", null)
                        .WithMany()
                        .HasForeignKey("AssignedSubTasksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesTodo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssingedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TodoUser", b =>
                {
                    b.HasOne("NotesTodo.Models.Todo", null)
                        .WithMany()
                        .HasForeignKey("AssignedTodosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NotesTodo.Models.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NotesTodo.Models.Todo", b =>
                {
                    b.Navigation("SubTask");
                });

            modelBuilder.Entity("NotesTodo.Models.TodoProject", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Todos");
                });

            modelBuilder.Entity("NotesTodo.Models.User", b =>
                {
                    b.Navigation("ProjectMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
